import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Homepage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Homepage</a>
        </h1>

        
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.sitecore.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Sitecore {' '}
          
        </a>
      </footer>
    </div>
  )
}
