import Head from 'next/head'
import Image from 'next/image'
import HeaderComponent from '../components/Homepage/header-component'
import styles from '../styles/Home.module.css'
import {getAllHomepage} from "../lib/Homepage/homepage-lib";
import Homepage from "../types/Homepage/homepage-type";
import FooterComponent from '../components/Homepage/footer-component';
import RecipeComponent from '../components/recipe-component';

export async function getStaticProps({ preview = false}){
  const allHomepage = await getAllHomepage(preview);
  return{
      props: {allHomepage, preview},
      // Next.js will attempt to re-generate the page:
      // - When a request comes in
      // - At most once every 10 seconds
      revalidate: 10, //in seconds
  }
}

type Props = {
  allHomepage: Homepage[];
}


const Homepage = ({allHomepage}: Props) => {
  //const homepage = allHomepage[0];
  console.log("Homepage: ")
  console.log(allHomepage);
  const homepage = allHomepage[0];
  const recipes = allHomepage[0].recipes.results;
  console.log(homepage);
  return (
    <div className={styles.container}>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <HeaderComponent 
          allHeaders={homepage.header}
        />
        <div>My Header Component</div>
     
        <h1 className={styles.title}>
          {homepage.recipeTitle}
        </h1>
        <p>{homepage.recipeSectionText}</p>
        <div>My Recipe List</div>
        {recipes.map((recipe: any) => (
          <RecipeComponent
              recipeTitle={recipe.Title}
              id={recipe.id}
              name={recipe.Name}
              ingredients={recipe.Ingredients}
              minutesToPrepare={recipe.Duration}
              preparationDescription={recipe.Description}
              image={recipe.ImageList.results[0].fileUrl}
          />
          ))}

        <div>My Footer</div>
        
        <FooterComponent
          allFooters={homepage.footer}
        />
        
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.sitecore.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Sitecore {' '}
          
        </a>
      </footer>
    </div>
  )
}
export default Homepage;
