import Head from 'next/head'
import Image from 'next/image'
import ReleasenotesComponent from '../components/releasenotes-component'
import { getAllReleaseNotes } from '../lib/releasenotes-lib'
import styles from '../styles/Home.module.css'
import rnstyles from '../styles/ReleaseNotes.module.css'
import ReleaseNote, {ReleaseNoteList} from '../types/ReleaseNotes/releaseNotes-type'


export async function getStaticProps({ preview = false}){
  const allReleaseNotes = await getAllReleaseNotes(preview);
  return{
      props: {allReleaseNotes, preview}
  }
}

type Props = {
  allReleaseNotes: ReleaseNote[];
}

const ReleaseNotes = ({allReleaseNotes}: Props) => {
  console.log(allReleaseNotes);
  //console.log("Page - Link ("+ allReleaseNotes[0].title +"): " + allReleaseNotes[0].linktooriginreleasenotes);
  //console.log("Page - Link ("+ allReleaseNotes[1].title +"): " + allReleaseNotes[1].linktooriginreleasenotes);
  return (
    <div className={styles.container}>
      <Head>
        <title>ReleaseNotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            ReleaseNotes
        </h1>

        <p className={styles.description}>
          Checkout the latest changes in Sitecore's composable check
        </p>

        <div className={styles.grid}>
          
          {allReleaseNotes.map((releaseNote: any) => (
              
          <ReleasenotesComponent key={releaseNote.id}
            ReleaseNote={releaseNote}
            /*id= {releaseNote.id}
            name= {releaseNote.name}
            linktooriginreleasenotes= {releaseNote.linktooriginreleasenotes}
            highlight= {releaseNote.highlight}
            addno= {releaseNote.addno}
            descriptionrt= {releaseNote.description}
            sitecoreProduct= 'DUMMY XM Cloud'
            sitecoreProductInternal= 'DUMMY Pages'
            title= {releaseNote.title}
            type= 'DUMMY Bugfix'
            breakingChange = {releaseNote.breakingChange}
            description = 'DUMMY Description ABC'
            context =  'DUMMY Context CDE'
            releases = 'DUMMY Release 1.0.0.0.1.0.1.01'*/
          />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export default ReleaseNotes;
